version: '3.8'
services:
  tokio-web-demo:
    image: ghcr.io/tsmt09/tokio-web-demo:latest
    pull_policy: always
    environment:
      REDIS_URL: "redis://redis:6379"
      WS_REFRESH_INTERVAL_MS: "100"
      RUST_LOG: DEBUG
    ports:
      - "8123:8123"
    depends_on:
      - keydb
    networks:
      - tokio-app

  keydb:
    image: eqalpha/keydb
    ports:
      - "6379:6379"
    healthcheck:
      test: ["CMD", "keydb-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - tokio-app

networks:
  tokio-app:
    driver: bridge
